# vim: sw=2

name: PushPackage

on:
  push:
  pull_request:
  release:
    types: [published]
  check_suite:
    types: [rerequested]

permissions:
  contents: read  # to fetch code (actions/checkout)
  packages: write # to create docker images

jobs:
  htmldocs:
    runs-on: ubuntu-24.04
    steps:
    - uses: oras-project/setup-oras@v2
      with:
        version: 1.3.1
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo Number of CPUs: $(nproc)
        echo "$GITHUB_CONTEXT"
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        submodules: false
        fetch-depth: 1
    - name: Tar doc
      run: |
        set -x
        tar -czf linuxcnc-doc.tar.gz -C docs/build html
    - name: Upload doc artifacts
      uses: actions/upload-artifact@v7
      with:
        name: linuxcnc-doc
        archive: false
        path: linuxcnc-doc.tar.gz
        if-no-files-found: error
